In [1]:
import numpy as np

In [2]:
english_score = np.array([55,89,76,65,48,70])

math_score = np.array([60,85,60,68,np.nan,60])

chinese_score = np.array([65,90,82,72,66,77])
# 1.請計算各科成績平均、最大值、最小值、標準差，其中數學缺一筆資料可忽略？
meanlist = np.array([english_score, math_score, chinese_score])
np.nanmean(meanlist, axis = 1)



array([67.16666667, 66.6       , 75.33333333])

In [3]:
np.nanstd(meanlist, axis = 1)

array([13.43399502,  9.70772888,  8.8254682 ])

In [4]:
np.nanmax((english_score,math_score, chinese_score), axis = 1)

array([89., 85., 90.])

In [5]:
np.nanmin((english_score,math_score, chinese_score), axis = 1)

array([48., 60., 65.])

In [6]:
math_score[4] = 55
math_score

array([60., 85., 60., 68., 55., 60.])

In [7]:
print(np.mean(math_score))
print(np.std(math_score))
print(np.max(math_score))
print(np.min(math_score))

64.66666666666667
9.860132971832694
85.0
55.0


In [8]:
BV = np.corrcoef((chinese_score, math_score))

In [9]:
CV = np.corrcoef((chinese_score, english_score))

In [15]:
if np.all(np.greater_equal(BV, CV)) == False:
    print ("英文有更好的相關係數")
else:
    print ("數學有更好的相關係數")

英文有更好的相關係數
